title: Ashkan Pakzad # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Deeplearning for Medical Image Analysis, University College London PhD student, Photogrammetry, boats and making things.
  <b>Articles on medium</b>
  <br><br>
  <a href="https://www.twitter.com/ashkanpakzad">Twitter</a>
  <br>
  <a href="https://www.medium.com/@ashkanpakzad">Medium</a>
  <br>
  <a href="https://www.instagram.com/quarknotes">Instagram</a>
  <br>
  <a href="https://sketchfab.com/ashkanpakzad">Sketchfab</a>
  <br>
  <a href="https://orcid.org/0000-0002-0802-5590">Orcid ID</a>
  <br>
  <a href="https://www.linkedin.com/in/apakzad/">LinkedIn</a>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
